# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - findjob

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Anaconda-Action
      id: step1
      uses: fdiblen/anaconda-action@0.1.7
      with:
        envName: "base"
        envFileName: 'environment_droplet.yml'
        
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: |
         cd api
         chmod +x mvnw
         ./mvnw clean package -DskipTests -Denv=cloud
        # mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/api/target/*.jar'
      - name: Upload python scripts for deployment
        uses: actions/upload-artifact@v3
        with:
          name: python-scripts
          path: '${{ github.workspace }}/*.py'
      - name: Upload bash scripts for deployment
        uses: actions/upload-artifact@v3
        with:
          name: bash-scripts
          path: '${{ github.workspace }}/api/*.sh'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      - name: Download python scripts
        uses: actions/download-artifact@v3
        with:
          name: python-scripts
      - name: Download bash scripts
        uses: actions/download-artifact@v3
        with:
          name: bash-scripts
      - uses: actions/checkout@v2
      - name: Anaconda-Action
        id: step1
        uses: fdiblen/anaconda-action@0.1.7
        with:
          env-name: "base"
          env-file-name: 'environment_droplet.yml'
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'findjob'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_49024A1C53B74DF9B2E9CD5E199A3F95 }}
          package: '*.jar'
